### PR TITLE
Bump k8s and controller runtime version

### PR DESCRIPTION
**Pull request by Jeffwan**
Current Kubernetes version is a little bit low, controller-runtime has more improvement and bug fixes in latest version. This PR upgrade the dependency version. This get ready for upgrading to latest version of kubeflow common. 

1. Upgrade Kubernetes to 1.15.10
2. Upgrade controller-runtime to 0.3.0 which is compatible with k8s 1.15.10

After the upgrade, we need to make two changes inside the code. 

1. `List` arguments sequences has been changed, see details in

https://github.com/kubernetes-sigs/controller-runtime/blob/release-0.1/pkg/client/interfaces.go#L54

https://github.com/kubernetes-sigs/controller-runtime/blob/release-0.3/pkg/client/interfaces.go#L61

2. `GetRecorder`  has been changed to `GetEventRecorderFor`, see details in 

https://github.com/kubernetes-sigs/controller-runtime/blob/release-0.1/pkg/manager/manager.go#L77-L78

https://github.com/kubernetes-sigs/controller-runtime/blob/release-0.3/pkg/manager/manager.go#L78-L79

Signed-off-by: Jiaxin Shan <seedjeffwan@gmail.com>

### CODE REVIEW

**Comment by Jeffwan** [comment]
Rebase timeout fix from https://github.com/kubeflow/xgboost-operator/pull/70/files and let's see if tests can pass

**Comment by terrytangyuan** [comment]
Thanks please ping when ready.

**Comment by Jeffwan** [comment]
before this change, Travis CI takes `succeeded 15 minutes ago in 2m 39s`, because of 1.15 dependencies, it takes `succeeded 1 minute ago in 5m 7s`.  This is expected because Kubernetes dependency becomes larger and larger, it takes more time to download go modules and finish build. 

presubmit job also need more time. After I set timeout to 30mins, it pass now. 

@terrytangyuan

**Comment by terrytangyuan** [comment]
Sounds good. Thanks!  
/lgtm
/approve

**Pull request merged**
