### PR TITLE
Add notice before archiving

### PR DESCRIPTION
**Pull request by terrytangyuan**
/cc @kubeflow/wg-training-leads 

Signed-off-by: terrytangyuan <terrytangyuan@gmail.com>

### CODE REVIEW

**Review by gaocegege — COMMENTED** [review]
/lgtm
/approve

**Review by gaocegege — COMMENTED** [review]
/lgtm
/approve

**Review by Jeffwan — APPROVED** [review]

**Comment by merlintang** [comment]
I have one comment here. Does the related examples (e.g., XGBOOST or LGBM example) provided in the training operator already?

**Comment by terrytangyuan** [comment]
Good catch. We only migrated the xgboost example. Let me move the other examples as well.

**Pull request merged**
