### PR TITLE
Fixes #111: wrong variable scope

### LINKED ISSUE #111: BUG: wrong variable scope results in undefined pointer
Hello,

I think I found the cause of issue #92.

https://github.com/kubeflow/xgboost-operator/blob/56c2c07525a826c285cf0efed99e636edddb676f/pkg/controller/v1/xgboostjob/xgboostjob_controller.go#L82-L115

In the code snippet mentioned above, `kcfg` is defined on line 82, assigned value on line 99, which is absolutely valid. However, it is initialized in a nested scope on line 103, which is a totally different variable than the programmer wanted to reference. Thus, when `mode == "in-cluster"`, `kcfg` will always be `nil` on line 115.

Here's a link to go playground that describes this bug: https://play.golang.org/p/1AkegfJ2O1G

code snippet:

```go
package main

import (
	"fmt"
)

func main() {
	var num int
	foo := 1
	if foo == 1 {
		num, err := getNum()
		if err != nil {
			panic("error")
		}
		_ = num
	}
	fmt.Println("Num is", num)
}

func getNum() (int, error) {
	return 123, nil
}
```

### PR DESCRIPTION
**Pull request by halftan**

### CODE REVIEW

**Comment by halftan** [comment]
@googlebot I signed it!

**Review by terrytangyuan — APPROVED** [review]
/lgtm
/approve

**Comment by terrytangyuan** [comment]
Could you fix the CI?

**Comment by halftan** [comment]
@terrytangyuan rebased to the latest master branch with new `go mod tidy` code change. This should fix the CI. Please review. Thanks.

**Review by terrytangyuan — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
