### PR TITLE
XGBoost Operator: Move manifests development upstream

### PR DESCRIPTION
**Pull request by yanniszark**
### Issue Resolved

Resolves: https://github.com/kubeflow/xgboost-operator/issues/109
Umbrella issue: https://github.com/kubeflow/manifests/issues/1740

### Description

As part of the work of wg-manifests for 1.3
(https://github.com/kubeflow/manifests/issues/1735), we are moving manifests
development in upstream repos. This gives the application developers full
ownership of their manifests, tracked in a single place.

This PR copies the manifests for application `XGBoost Operator`
from path `apps/xgboost-job/upstream` of kubeflow/manifests to path
`config` of the upstream repo (https://github.com/kubeflow/xgboost-operator).

cc @kubeflow/wg-training-leads

### CODE REVIEW

**Comment by yanniszark** [comment]
@kubeflow/wg-training-leads the build is failing because of a Go error:
```
go: error loading module requirements
The command "go build ./..." exited with 1.
```

This PR doesn't change any files that affect the go build.
Could you please take a look? Was the CI in a broken state?

**Review by terrytangyuan — APPROVED** [review]
/lgtm
Others PTAL @kubeflow/wg-training-leads

**Comment by yanniszark** [comment]
@kubeflow/wg-training-leads kind ping.
Could you please take a look at the CI?
The build is failing because of a Go error:
```
go: error loading module requirements
The command "go build ./..." exited with 1.
```

This PR doesn't change any files that affect the go build.
Could you please take a look? Is the CI in a broken state?

**Comment by terrytangyuan** [comment]
Looks like one of the dependencies have been made private/removed:
```
go: github.com/mholt/caddy@v0.0.0-20180213163048-2de495001514: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/travis/gopath/pkg/mod/cache/vcs/495ea6777f0db69d94a5e13536e287e8ffc69f32bd5b40c3c5b793f0ccb033ee: exit status 128:

	remote: Invalid username or password.

	fatal: Authentication failed for 'https://github.com/mholt/caddy/'
```

**Comment by terrytangyuan** [comment]
Given that this is direct copy from kubeflow/manifest, I think we can manually merge this for now. Others from @kubeflow/wg-training-leads  PTAL.

**Comment by terrytangyuan** [comment]
Could you update instructions on `README` since we no longer install from `kubeflow/manifests`?

**Review by gaocegege — COMMENTED** [review]
/lgtm

Thanks for your contribution! :tada: :+1:

**Pull request merged**
